#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import { join, extname } from 'path';

const BASELINE_FILE = 'quality-gate-baseline.json';
const COVERAGE_FILE = 'coverage/coverage-summary.json';
const SRC_DIR = 'src';
const LINE_LIMIT = 300;

const command = process.argv[2] ?? 'check';

function readJson(path) {
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function writeJson(path, data) {
  writeFileSync(path, JSON.stringify(data, null, 2) + '\n');
}

function getCoverageMetrics() {
  const summary = readJson(COVERAGE_FILE);
  if (!summary?.total) return null;
  const { total } = summary;
  return {
    lines: total.lines.pct,
    statements: total.statements.pct,
    functions: total.functions.pct,
    branches: total.branches.pct,
  };
}

function walkSrc(dir, results = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!['node_modules', '.astro', 'dist', 'coverage', '.git'].includes(entry.name)) {
        walkSrc(fullPath, results);
      }
    } else if (['.ts', '.tsx', '.js', '.jsx'].includes(extname(entry.name)) && !entry.name.endsWith('.types.ts')) {
      results.push(fullPath);
    }
  }
  return results;
}

function getOversizedFiles() {
  const files = walkSrc(SRC_DIR);
  return files
    .map(f => {
      const lines = readFileSync(f, 'utf-8').split('\n').length;
      return { file: f.replace(process.cwd() + '/', ''), lines };
    })
    .filter(f => f.lines > LINE_LIMIT);
}

function countAnyUsage() {
  const files = walkSrc(SRC_DIR).filter(f => ['.ts', '.tsx'].includes(extname(f)));
  return files.reduce((count, f) => {
    const matches = readFileSync(f, 'utf-8').match(/:\s*any\b/g);
    return count + (matches?.length ?? 0);
  }, 0);
}

function collectCurrentMetrics() {
  const coverage = getCoverageMetrics();
  const oversizedFiles = getOversizedFiles();
  const anyCount = countAnyUsage();
  return {
    timestamp: new Date().toISOString(),
    coverage: coverage ?? { lines: 0, statements: 0, functions: 0, branches: 0 },
    violations: {
      oversizedFiles: oversizedFiles.length,
      anyTypeUsage: anyCount,
    },
    _oversizedFilesList: oversizedFiles,
  };
}

function delta(current, baseline) {
  return +(current - baseline).toFixed(2);
}

function sign(n) {
  if (n > 0) return `+${n}`;
  if (n < 0) return `${n}`;
  return '—';
}

function pct(n) {
  return `${Number(n).toFixed(2)}%`;
}

function generateReport(current, baseline) {
  const regressions = [];

  const coverageRows = ['Lines', 'Statements', 'Functions', 'Branches'].map(m => {
    const key = m.toLowerCase();
    const b = baseline.coverage[key] ?? 0;
    const c = current.coverage[key] ?? 0;
    const d = delta(c, b);
    if (d < 0) regressions.push(`${m} coverage caiu ${Math.abs(d)}%`);
    return `| ${m} | ${pct(b)} | ${pct(c)} | ${sign(d)}% |`;
  });

  const oversizedDelta = current.violations.oversizedFiles - (baseline.violations?.oversizedFiles ?? 0);
  const anyDelta = current.violations.anyTypeUsage - (baseline.violations?.anyTypeUsage ?? 0);
  if (oversizedDelta > 0) regressions.push(`Arquivos oversized aumentaram (+${oversizedDelta})`);
  if (anyDelta > 0) regressions.push(`Uso de \`any\` aumentou (+${anyDelta})`);

  const passed = regressions.length === 0;

  const lines = [
    '## Quality Gate',
    '',
    `**Status: ${passed ? '✅ Passed' : '❌ Failed'}**`,
    '',
    '### Coverage',
    '',
    '| Metric | Baseline | Current | Δ |',
    '|--------|----------|---------|---|',
    ...coverageRows,
    '',
    '### Violations',
    '',
    '| Metric | Baseline | Current | Δ |',
    '|--------|----------|---------|---|',
    `| Arquivos oversized (>${LINE_LIMIT} linhas) | ${baseline.violations?.oversizedFiles ?? 0} | ${current.violations.oversizedFiles} | ${sign(oversizedDelta)} |`,
    `| \`any\` type usage | ${baseline.violations?.anyTypeUsage ?? 0} | ${current.violations.anyTypeUsage} | ${sign(anyDelta)} |`,
  ];

  if (current._oversizedFilesList.length > 0) {
    lines.push('', '### Arquivos Oversized', '');
    for (const f of current._oversizedFilesList) {
      lines.push(`- \`${f.file}\` — ${f.lines} linhas`);
    }
  }

  if (regressions.length > 0) {
    lines.push('', '### Regressões', '');
    for (const r of regressions) {
      lines.push(`- ${r}`);
    }
  }

  lines.push('', `_Generated by \`scripts/quality-gate.js\` on ${current.timestamp}_`);

  return { report: lines.join('\n'), passed, regressions };
}

function saveBaseline(metrics) {
  const toSave = { ...metrics };
  delete toSave._oversizedFilesList;
  writeJson(BASELINE_FILE, toSave);
}

function requireCoverage() {
  if (!existsSync(COVERAGE_FILE)) {
    console.error(`❌ ${COVERAGE_FILE} não encontrado.`);
    console.error('   Rode: pnpm test:unit --coverage');
    process.exit(1);
  }
}

if (command === 'init') {
  if (existsSync(BASELINE_FILE)) {
    console.log(`⚠️  ${BASELINE_FILE} já existe. Use 'update' para substituir.`);
    process.exit(0);
  }
  requireCoverage();
  const metrics = collectCurrentMetrics();
  saveBaseline(metrics);
  console.log(`✅ Baseline criado: ${BASELINE_FILE}`);
  console.log(`   Coverage: lines=${pct(metrics.coverage.lines)} statements=${pct(metrics.coverage.statements)} functions=${pct(metrics.coverage.functions)} branches=${pct(metrics.coverage.branches)}`);
  console.log(`   Violations: oversized=${metrics.violations.oversizedFiles} any=${metrics.violations.anyTypeUsage}`);
  process.exit(0);
}

if (command === 'update') {
  requireCoverage();
  const metrics = collectCurrentMetrics();
  saveBaseline(metrics);
  console.log(`✅ Baseline atualizado: ${BASELINE_FILE}`);
  process.exit(0);
}

if (command === 'check') {
  const baseline = readJson(BASELINE_FILE);
  if (!baseline) {
    console.error(`❌ ${BASELINE_FILE} não encontrado.`);
    console.error('   Rode: pnpm test:unit --coverage && node scripts/quality-gate.js init');
    process.exit(1);
  }
  requireCoverage();

  const current = collectCurrentMetrics();
  const { report, passed, regressions } = generateReport(current, baseline);

  console.log(report);

  writeFileSync('quality-gate-report.md', report);

  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (summaryFile) {
    writeFileSync(summaryFile, report);
  }

  if (!passed) {
    console.error(`\n❌ Quality Gate falhou:\n${regressions.map(r => `   • ${r}`).join('\n')}`);
    process.exit(1);
  }

  console.log('\n✅ Quality Gate passou.');
  process.exit(0);
}

console.error(`Comando desconhecido: "${command}". Uso: init | check | update`);
process.exit(1);
